Repository thinktocode/COVID-19-Tracker, pull requests merged in 2021-01, with the labels that each got.

#8 Implemented New Feature
  README.md
Labels: DWOC, Level-4

#10 Redesign of UI
  CODE_OF_CONDUCT.md
Labels: DWOC, Level-5

#12 Added config file for Welcome BOT
  .github/config.yml
Labels: DWOC, Level-2

#14 README FILE BADGES INTRODUCED
  README.md
Labels: DWOC, Level-2

#17 Update in the README badges
  README.md
Labels: DWOC, Level-1

#20 Pie Chart Issue solved
  app/src/main/java/com/hari/covid_19app/ui/item/ItemStatisticsCard.kt
  app/src/main/res/layout/item_statistics_card.xml
Labels: DWOC, Level-4

#21 Add tharunc
  .github/ISSUE_TEMPLATE.md/bug.md
  .github/ISSUE_TEMPLATE.md/documentation.md
  .github/ISSUE_TEMPLATE.md/feature.md
  .github/ISSUE_TEMPLATE.md/proposal.md
Labels: DWOC, Level-2

#24 created opensource section in readme
  README.md
Labels: DWOC, Level-1

#27 UI Redesign
  app/debug/output-metadata.json
Labels: DWOC, Level-5

#29 Bug Fix
  README.md
Labels: DWOC, Level-5

#31 Upgrade
  LICENSE
Labels: DWOC, Level-5

#33 Add Contributors Table in README.md
  README.md
Labels: DWOC, Level-1
